#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import math
def quadratic(a,b,c):

	i=b*b-4*a*c
	if i < 0:
		print('no answer')

	elif i == o:
		print('only one answer:',x1=x2=-b/(2*a))
	
	else:
		print('two answers:',x1=(-b+math.sqrt(i))/(2*a),x2=((-b-math.sqrt(i))/(2*a)))

